### PR TITLE
Fix User objects not saving, Add support for Parse Files, Anonymous Login

### PR DESCRIPTION
**Pull request by klanmiko**
Hi Phil,

I am using your sdk to develop an application for our hackathon participants. I ran over a few issues that I fixed and I thought it woud be a good idea to contribute back to this project. Here are my changes:

* Fixed changes on User object not syncing to server due to missing session token when accessing API
* Added the ability to login anonymously by providing "AUTH_DATA" POST data with a unique UUID. Can be extended to allow for facebook and twitter auth in the future
* Added the ability to create a Parse file with a url and name and download the file to temporary storage
* Fixed bug with ParseFile initialized to null _file value.

Let me know if these need work

### CODE REVIEW

**Comment by klanmiko** [comment]
helps with #36

**Comment by ScanEat** [comment]
Hi klanmiko, are you sure parse files works ?

Because I tested with a new "picture" column with png file.

And when I print the payload, I have this sample:

```
"picture":"{\"__type\": \"Pointer\", \"className\": \"File\", \"objectId\": \"null\"}"}
```

**Comment by phillwiggins** [comment]
Amazing work. 

I'm happy to merge and will test tonight to ensure the file upload is working correctly. 

Thanks!

**Comment by klanmiko** [comment]
Thanks @phillwiggins! Thanks for making this library.

@ScanEat yes it works. The reason you see that is because the parse_encoder.dart encodes the object as a pointer and not a file. I think it is done this way for a specific reason...? to send to the server? Otherwise the print statements for the ParseUser and ParseFile, ParseGeo should be before that

**Comment by ScanEat** [comment]
Ok @klanmiko but can you show us a code sample to retrieve the picture.url from database ?

**Comment by rodrigosmarques** [comment]
Hi Guys,
Have you checked the ParseFile upload is working?
Do you have any sample code to send me?

**Comment by phranck** [comment]
@klanmiko You added support for anon login, which is great! 😊 However, I wonder how to check if the `currentUser` is an anonymous user? Do you have a suggestion?

Thanks in advance!

**Comment by danibjor** [comment]
@phranck you can check if 
```
var user = await ParseUser.currentUser();
if (user != null && user['userData'] != null && user['userData']['anonymous'] != null) { 
  // do anonymous user stuff
}
```

**Pull request merged**
