### PR TITLE
Implemented whereRelatedTo query

### PR DESCRIPTION
**Pull request by sidiabale**
Added the whereRelatedTo query for Parse Relations including unit test

### CODE REVIEW

**Comment by sidiabale** [comment]
You're welcome. Any idea when this version will be published?

**Comment by phillwiggins** [comment]
Later today I will ensure this is published.

I think theres a few peices of work that are on master that need merging to
the release branch, then some tests need to be done.

**Comment by sidiabale** [comment]
@phillwiggins Any update on when this release will be available via Dart Pub?

**Comment by phillwiggins** [comment]
Hey Chidiebere

Hopefully soon. These been reports of saving issues in the latest version
which we're trying to test now.

**Comment by sidiabale** [comment]
Hey Phill,

Any update on this?

**Comment by phillwiggins** [comment]
Hey

Updated as of yesterday.

Looks to be a big with regards to relations. That's hopefully being fixed
and updated very soon.

**Comment by sidiabale** [comment]
Hey,

Nice to hear the release is live. All the best with having the bug fixed.

Op ma 24 jun. 2019 22:13 schreef Phill Wiggins <notifications@github.com>:

**Pull request merged**
