### PR TITLE
Fix Installation timezone TODO.

### PR DESCRIPTION
**Pull request by yulingtianxia**

### CODE REVIEW

**Comment by yulingtianxia** [comment]
@phillwiggins FlutterNativeTimezone use channel to call iOS/Android API.

**Comment by vanyasem** [comment]
Why was this merge request reverted?

**Comment by mtrezza** [comment]
Can you find the PR that reverted this?

**Comment by vanyasem** [comment]
@mtrezza I think it was lost in the transition to separate packages : https://github.com/parse-community/Parse-SDK-Flutter/commit/e35d28dcc64a0dd81df985c5ad713dc1295d14f4#diff-516d9c6a712fc209bf5505f80fe71c1b1f5e3859b497067a9f2666ccefbc11b8

**Comment by vanyasem** [comment]
It was first introduced in release 1.0.22 - https://github.com/parse-community/Parse-SDK-Flutter/commits/release/1.0.22/lib/src/objects

But in release 1.0.23 it's already gone - https://github.com/parse-community/Parse-SDK-Flutter/commit/130121e2ff66db930739b93dcce31b577061ae0a#diff-c37936a338cd43591644ae6be29c5da6ee8b18fd681cb3c584f417b8c9017f24

**Comment by vanyasem** [comment]
image

**Comment by RodrigoSMarques** [comment]
To use this package it is necessary to include consistency for Flutter WEB, as there is no support.

For this reason the PR was scrapped.

If you don't use Flutter Web, you can include the call directly in your project, after creating the Installation.

**Pull request merged**
