### PR TITLE
Fix ParseUser logout() methode

### PR DESCRIPTION
**Pull request by chrbayer**
Fix for #83

- Set the return type to Future<ParseResponse>
- sessonId has to be stored and used locally because it is cleared inside the function
- check for username useless

### CODE REVIEW

**Comment by chrbayer** [comment]
Your are incredible fast :-)

**Comment by rickspencer3** [comment]
Are you going to merge these improvements ?

**Comment by phillwiggins** [comment]
Apologies, I thought I had done that already!

Sorry for the delay.

**Comment by rickspencer3** [comment]
Don't apologize! You are a hero. Thanks for letting us help and taking care of this.

**Pull request merged**
