### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by WangPerryWPY**
Fix OrderBy multiple columns #241

### CODE REVIEW

**Comment by rodrigosmarques** [comment]
@WangPerryWPY 
Some changes that I have included in README.md are being removed in your PR.
## Storage
## Relation

**Comment by WangPerryWPY** [comment]
Sorry, I haven't found your changes. Can you give me a link? Thanks
 
 
------------------ Original ------------------

**Comment by rodrigosmarques** [comment]
[https://github.com/phillwiggins/flutter_parse_sdk/blob/release/1.0.23/README.md]

**Comment by phillwiggins** [comment]
@WangPerryWPY

Please can check the above issue. Also, please can you close this MR and create a new one on branch labelled release/1.0.23.

Thanks in advance

**Pull request closed without merging**
