### PR TITLE
Support Relation

### PR DESCRIPTION
**Pull request by yulingtianxia**

### CODE REVIEW

**Comment by rodrigosmarques** [comment]
Hi @yulingtianxia 
Add and Remove Relation is OK.
How should I access relationship objects?
I tried using getRelation, but not work?
Can you give an example?

**Comment by WahdanZ** [comment]
@rodrigosmarques 
in query builder, you should use this 
queryBuilder.includeObject(["field"]);

**Comment by rodrigosmarques** [comment]
@WahdanZ 
include doesn't work with Relations, only with Pointers

https://github.com/parse-community/parse-server/issues/4138
https://github.com/parse-community/parse-server/issues/2850
https://stackoverflow.com/questions/45645985/parse-sdk-android-query-with-relation-using-include-is-not-working

**Comment by yulingtianxia** [comment]
To Retrive a relation instance for user, call:
 ```dart
 final relation = user.getRelation('dietPlans');
 ```

**Comment by rodrigosmarques** [comment]
@yulingtianxia 
I did the process as directed.
I tried to add a new item to the relationship and it didn't work

My code:
```dart
    final parseRelation = resultTestAPI.getRelation('produtoRelation');
    parseRelation.add(ParseObject("Produto")..set("objectId", "XGadzYxnac"));
    apiResponse = await parseObject.save();
``
![Captura de Tela 2019-08-04 às 23 07 17](https://user-images.githubusercontent.com/17687286/62434047-6d6f9d80-b70d-11e9-86a0-86da9de59c68.png)

![Captura de Tela 2019-08-04 às 23 09 12](https://user-images.githubusercontent.com/17687286/62434053-71032480-b70d-11e9-94a6-c70b1be1e4c4.png)

![Captura de Tela 2019-08-04 às 23 10 54](https://user-images.githubusercontent.com/17687286/62434058-76f90580-b70d-11e9-8d17-a3503b8ed403.png)

**Pull request merged**
