### PR TITLE
Fix OrderBy multiple columns

### PR DESCRIPTION
**Pull request by rodrigosmarques**
Fix OrderBy multiple columns

### CODE REVIEW

**Comment by pastordee** [comment]
OrderBy is not working any more
when you have more than one OrderBy I get this error
flutter: NoSuchMethodError: The method '+' was called on null.
Receiver: null
Tried calling: +(",")

and when OrderBy is just one query don't show and know error shows.

**Comment by rodrigosmarques** [comment]
This is strange. See my debug.

My query:

```dart
  QueryBuilder<ParseUser> queryBuilder =
      QueryBuilder<ParseUser>(ParseUser.forQuery())
        ..orderByAscending("runCount")
        ..orderByAscending('createdAt')
        ..orderByDescending('updatedAt')
        ..whereEqualTo("tipo", "D")
        ..whereGreaterThanOrEqualsTo(
           "createdAt", DateTime.now().subtract(Duration(days: 90)))
        ..whereLessThanOrEqualTo("createdAt", DateTime.now());
  apiResponse = await queryBuilder.query();
```
Debug Parse Query. 3 fields on order by 
Captura de Tela 2019-08-07 às 17 21 04
Captura de Tela 2019-08-07 às 17 21 53
Captura de Tela 2019-08-07 às 17 22 24

Curl, see order on final URL
```dart
curl -X GET -H 'user-agent: Flutter Parse SDK 1.0.23' -H 'X-Parse-Application-Id: xxxxxxxxxxxx' -H 'X-Parse-Session-Token: xxxxxxxxxx' -H 'X-Parse-Client-Key: xxxxxxxxxx' https://xxx.xxxx.xxx/1/classes/_User?where=%7B%22tipo%22:%20%22D%22,%22createdAt%22:%7B%20%22$gte%22:%7B%22__type%22:%22Date%22,%22iso%22:%222019-05-09T20:22:30.782Z%22%7D,%20%22$lte%22:%7B%22__type%22:%22Date%22,%22iso%22:%222019-08-07T20:22:30.784Z%22%7D%7D%7D&order=runCount,createdAt,-updatedAt
```

**Comment by pastordee** [comment]
var queryBuilder = QueryBuilder<User>(User(null, null,null))
            ..setAmountToSkip(pageIndex)
            ..setLimit(pageLimit)
            ..whereNotContainedIn("objectId", globals.user.buddies)
            ..orderByAscending(User.keyOnline)
            ..orderByDescending(User.keyLastSeen);
final prayersResponse = await  queryBuilder.query();

I have done everything and is still not work.

**Comment by rodrigosmarques** [comment]
@pastordee 
Is User a custom object?
Was it working before my PR?
Before the query, what is the result for User.keyOnline and User.keyLastSeen?
Does this contain the value or name of the field?
```dart
print(User.keyOnline);print(User.keyLastSeen);
```

**Comment by pastordee** [comment]
hi thanks for your quick reply

I remove this two lines 
..setAmountToSkip(pageIndex)
..setLimit(pageLimit)
and it works perfectly

**Comment by rodrigosmarques** [comment]
@pastordee 
I will test with these conditions. It may actually have an error.

**Comment by pastordee** [comment]
@rodrigosmarques 
Thanks

**Comment by rodrigosmarques** [comment]
@pastordee 
There really is an error.
I'm making adjustments

**Comment by rodrigosmarques** [comment]
@pastordee 
New PR #243

**Comment by pastordee** [comment]
nice one is all work fine thanks.

**Pull request merged**
