### PR TITLE
Added support for Geo Queries:

### PR DESCRIPTION
**Pull request by rodrigosmarques**
Added support for Geo Queries:
- whereNear
- whereWithinMiles
- whereWithinKilometers
- whereWithinRadians
- whereWithinGeoBox

### CODE REVIEW

**Comment by phillwiggins** [comment]
Good work!

**Comment by rodrigosmarques** [comment]
Phill
I am not able to use the changes with version 1.0.13 even after downloading the package again. Will you publish a new release?

**Comment by phillwiggins** [comment]
Hey

I'll do that right now.

It will be 1.0.14 with your changes.

**Comment by phillwiggins** [comment]
Released 😁

**Pull request merged**
