### PR TITLE
Save recursively

### PR DESCRIPTION
**Pull request by yulingtianxia**
1. Support save objects recursively.  
2. Fix encoding for Add and Remove operations.
3. Fix some exceptions.
4. Support batch request and handle response.

### CODE REVIEW

**Comment by yulingtianxia** [comment]
There are a lot of things to do:
1. Check `dirty` objects and unsaved changes.
2. Reconstruction Add, Remove, AddRelation, RemoveRelation ... Array operations should be incremental.
3. Complete features in ACL.

**Comment by phillwiggins** [comment]
Great work.

It looks like a large amount of changes. I will have to review them and run some tests, but happy to merge this branch for now,

**Comment by rodrigosmarques** [comment]
Hi,
I tried running this version and I have the following errors.
It's calling Sebast, I do not remember who made the change, but had suggested to leave SharedPreference with default.

```dart
Launching lib/main.dart on iPhone Xʀ in debug mode...
Xcode build done.                                           12,0s
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
#1      XXTEA._fixkey
#2      XXTEA.encrypt
#3      XXTEA.encryptToString
#4      _XXTeaEncoder.convert
#5      Codec.encode  (dart:convert/codec.dart:21:32)
#6      getCodecEncodedSignature
#7      SembastDatabase.open.<anonymous closure>._openDone
<asynchronous suspension>
#8      SembastDatabase.open.<anonymous closure>
<asynchronous suspension>
#9      BasicLock.synchronized
<asynchronous suspension>
#10     SembastDatabase.open (p<…>
```

**Comment by yulingtianxia** [comment]
@rodrigosmarques Have you ever tried the previous version? Perhaps it's a data issue.

**Comment by zenz** [comment]
@rodrigosmarques Hi, 
Did you solve the issue of 
"[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null.

How did you solve it? is that some internal function name changed so makes this error?

**Comment by zenz** [comment]
I had figure out why this issue happened.
verison 1.0.22 need masterKey while do Parse().initialize().
When those functions don't need masterKey permission, please don't ask for it.

**Comment by rodrigosmarques** [comment]
HI @zenz 
Use await in Parse().initialize.
It was one of the changes that occurred in version 22

```dart
await Parse().initialize("xxxxxxxxxx",
      "xxxxxxxxxxxxxx",
      autoSendSessionId: true,
      liveQueryUrl: "xxxxxxxxxxxxxx");
  ```

**Pull request merged**
